### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by artslob** [unishubh/Pynux#1]
Hi
Project right now have files that should not be in vcs (e.g. .pyc and .idea). This can be fixed with .gitignore file.

Would it be ok to make pull request for this project?

**Comment by thepabloaguilar** [comment]
This issue has been fixed, close it.

**Comment by artslob** [comment]
Yes, it can be closed, but `.idea` folder still presented in git

**Comment by thepabloaguilar** [comment]
I opened new PR to delete that folder! #6

**Comment by artslob** [comment]
@phakiller Good! Do you want *me* to close this issue? Project holder can close it after he merge #6.  
Also you can write `closes #1` in #6 comments, it should automatically close issue when it merged.
But I am not sure, maybe you should have [put it in body](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/) of PR.

**Comment by thepabloaguilar** [comment]
@artslob Done! Hahahaha
Nice tip & trick!!
